### ISSUE TITLE
Magic instance classes can be used as values

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#108]
We should create dynamic wrappers for these in the runtime lib. Something like...

```Lua
TS.Instance = setmetatable({}, {
	__index = function(self, className)
		local wrapper = {
			new = function(parent)
				return Instance.new(className, parent)
			end
		}
		self[className] = wrapper
		return wrapper
	end
})
```

so that
```TS
new Part();
```
becomes
```Lua
TS.Instance.Part.new();
```

**Comment by Validark** [comment]
Why would we want to do this?

**Comment by Validark** [comment]
Instead, when needed, we can generate them inline.

```lua
function () return Instance.new("Part") end
```

**Comment by evaera** [comment]
> Instead, when needed, we can generate them inline.
> 
> ```lua
> function () return Instance.new("Part") end
> ```

Because we're treating these types as values, we don't need the instance itself, but rather the "constructor object" for each instance. This is necessary so that you can pass `Part` itself as a value and then instantiate it somewhere else. Since these types of instances do not have built in constructor objects in Roblox, we need to put them in the runtime library,

**Comment by Validark** [comment]
If you pass `Part` itself, than sure, but there is no reason to go through the run-time library for a direct call to `new Part()`

**Comment by osyrisrblx** [comment]
I think I can detect the case of `new Part()` and optimize that
