### ISSUE TITLE
roblox-ts should have a camelCased roblox api function and properties

### ISSUE THREAD

**Issue by ViniDalvino** [roblox-ts/roblox-ts#1184]
## Suggestion
Every function and properties of the roblox api have it's camel cased equivalent. I suggest to add them into the typedefiniton of roblox ts as it's going to give roblosx ts a bigger JS vibe.

## Use Cases
I want to use it to have a more js-like vibe as most of JS method are camelCased.

## Examples
`workspace.findFirstChild("brick")`
`print("The default orientation of mobile screen is", game.StarterGui.screenOrientation)`

**Comment by Visualizememe** [comment]
I definitely agree with this. Having PascalCase in a JS/TS library makes little to no sense, and contradicts with the common approach of libraries.

In addition, it's mildly annoying when my IDE (WebStorm EAP) thinks that all properties with PascalCase naming conventions are classes, because it then will not display the properties should I start writing camelCase, although this is my fault.

**Comment by osyrisrblx** [comment]
There's no guarantee Roblox will always support the camelCase API since it's undocumented.

Converting at compile time isn't possible.

**Comment by Dionysusnu** [comment]
By always, do you mean "for every API member", or "in the future"?
The former is obviously a deal breaker, but the latter doesn't prevent us from adding the types while it still is supported.

**Comment by osyrisrblx** [comment]
> By always, do you mean "for every API member", or "in the future"?
I mean in the future. Right now, there's an internal mechanism that automatically converts camelCase lookups into PascalCase lookups. This is _slightly_ slower since it has to first make sure the camelCase version does not exist before attempting to check the PascalCase version.

And Roblox does not document this behavior anywhere (as far as I know), so it could be removed at any point.

I'd prefer not to duplicate every method/property/etc. in the types. That would make intellisense a lot less useful.
