### ISSUE TITLE
Values typed as Iterable<T> cannot be iterated with for-of loops. 

### ISSUE THREAD

**Issue by jagatse** [roblox-ts/roblox-ts#1202]
## Version

**roblox-ts:** 1.0.0-beta.11

**@rbxts/types:** N/A

## Description

The compiler crashes when a for-of loop is used on a value typed as `Iterable<T>`.  The type of T does not seem to matter. Attempts to loop over an `Iterable<number>` also fails.

## Minimal Reproduction

```typescript
function getFirst<T>(items: Iterable<T>) {
    for (const item of items) {
        return item;
    }
}
```

**Expected behavior:**

Compiler produces working code.

**Current behavior:**

```
-- Error: Assertion Failed! ForOf iteration type not implemented: Iterable<T>
-- This is a compiler bug! Please submit a bug report here:
-- https://github.com/roblox-ts/roblox-ts/issues
```

## Playground link
[Link here](https://roblox-ts.com/playground/#code/GYVwdgxgLglg9mABAcwKZQGIwE4GcoA8AKgHwAUMUqAtrgFyICSV2AhgEYA2qxJAlIgDeAKERjEwONkRkICfIko1EcYIqq0BI8TsTZ0IbEiXUA3KPEBfYdaA).

**Comment by osyrisrblx** [comment]
I don't think we can fix this. There's not really a clear idea what an `Iterable<T>` is in Luau and how you would iterate over that.

What we _do_ have is several types (like `Array<T>, `Map<K, V>`, `Set<T>`) that all iterate in different ways.
Because of this, you have to be more specific in your types for the compiler to generate something.

Going to leave this issue open so that I can create a diagnostic error for this instead of just an assertion failure crash.
