### ISSUE TITLE
string.size vs string.length

### ISSUE THREAD

**Issue by codyduong** [roblox-ts/roblox-ts#1709]
I find it a bit odd that the [string length property ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length) is named string.size

```typescript
const s = 'fun'

print(s.length)
//Property 'length' does not exist on type 'string'.ts(2339)
```

EDIT: This was originally to address that there was no string.length, but I realized now it's called string.size.

Also is there any particular reason it's called size, versus length? I feel like all the documentation related to the # operator is called length?

**Comment by codyduong** [comment]
^
I guess this is a question of convention, is this a preference of roblox-ts that we use lua convention rather than web standards?

**Comment by Fireboltofdeath** [comment]
A method was chosen because roblox-ts uses macros which means it has to always have information about the method's origins to transform it properly. With a property macro, it's extremely easy to mistakenly pass in an object which is not expecting a macro. It's also possible to do this with a method, but it's less likely.
```ts
function takesLength(obj: { length: number }) {
  print(obj.length) // nil
}
takesLength([1, 2, 3]);
```

> I guess this is a question of conventions as well, is this a preference of roblox-ts that we use lua convention rather than web standard/ECMA? I find myself trying to use functions that aren't implemented in lua, and thus not defined here, (and would be normal valid JS/TS but not lua)

A lot of JS/TS API members were removed during the beta to prevent cluttering the API and preferring Lua functions where applicable.

> Related to this, is that object destructuring is not implemented.

[Object destructuring is supported](https://roblox-ts.com/playground/#code/MYewdgzgLgBA3jAhgGhgIxgXxgXnkgLhgEZU0iAmLIA) and you can see roughly what isn't supported syntax-wise [here](https://github.com/roblox-ts/roblox-ts/blob/master/src/Shared/diagnostics.ts#L118).
