### ISSUE TITLE
tsconfig.buildinfo should be overwritten when changing compile type with --type flag

### ISSUE THREAD

**Issue by murmanox** [roblox-ts/roblox-ts#1750]

**Comment by Dionysusnu** [comment]
This affects more than just the type flag - basically anything not from source files that affects conditional compilation. Things like the default.project.json, transformer config and non-type package file updates.
Currently, some of this is already fixed by hacking `ts.version`, adding a hash of the other sources, before generating the build info. This then causes a recompile later because it will believe the TS version changed.
My suggestion would be to add a `TransformState.registerNonSourceFileCondition`, which will register a piece of data to be included in the `ts.version` hash hack.
