### ISSUE TITLE
Use `stderr` for compile errors

### ISSUE THREAD

**Issue by grilme99** [roblox-ts/roblox-ts#1845]
Currently the roblox-ts CLI sends error messages to `stdout`. This makes processing them difficult, and piping them through `stderr` would vastly simplify things for me.

I'm currently writing an internal CLI to help simplify and standardize build and deployment processes. Part of this is making the compiler output simpler and easier on the eye.  To do this I am running the compiler as a child process and parsing its `stdout` to produce helpful status messages and process bars. 

However, I am currently unable to easily handle compiler errors because they are not piped through `stderr`, and pattern matching them is non-trivial because each error is split into multiple lines and thus separate entries in `stdout` when I consume it.

**Comment by osyrisrblx** [comment]
Closing this as I think it's best to follow TypeScript's example here.

https://github.com/microsoft/TypeScript/issues/12844

**Comment by Dionysusnu** [comment]
I'd say that same TS discussion has a very solid rebuttal: https://github.com/microsoft/TypeScript/issues/615#issuecomment-87582601
and discussed further down as well. TL;DR it's expected that failures go to stderr, TS made a bad design choice initially and would change it if it weren't for the breaking change now.
Because roblox-ts is a smaller project, and we are moving to 2.0, I think this breaking change is justified and a good decision.
