### ISSUE TITLE
Open VPN profile in repo

### ISSUE THREAD

**Issue by kthompson** [roblox-ts/roblox-ts#2047]
I noticed you have an open VPN profile in your repo that anyone could come and download and use to connect to. This type of thing is usually better put in GitHub secrets or something.

Since it is in the history now you would need to rewrite your history to remove it or disable the account that allows access to this VPN.

The profile was added in https://github.com/roblox-ts/roblox-ts/commit/403d44ac1dde5ba2f4a9b8f45970e8e43f67deda

**Comment by OverHash** [comment]
Unfortunately this is not a valid option. Adding the token under the GitHub secrets would not allow forks to use the test CI, because the secret does not exist on the fork. This would fail the CI.

**Comment by osyrisrblx** [comment]
The problem is that:

1. Roblox Studio needs authentication to start up
2. Using the same authentication token from different geolocations can result in it being invalidated
3. So we use OpenVPN to create / use a blank Roblox account authentication token
4. Forks don't get repository secrets (or their own for that matter), and CI is a lot less useful if it doesn't work on PRs from forks.

**Comment by kthompson** [comment]
Yea I didn't really know what it is for I just thought it was weird to store credentials in your repo and wanted to say something in case this was an accident or something 😃 If the intent is to share VPN access with the internet then this is fine.
