### ISSUE TITLE
--noStrict can not work

### ISSUE THREAD

**Issue by zaoqi** [roblox-ts/roblox-ts#254]

**Comment by zaoqi** [comment]
And strict can not be false.
```
Compiler Error: Invalid "tsconfig.json" configuration!
https://roblox-ts.github.io/docs/quick-start#project-folder-setup
- "strict" must be true
```

**Comment by evaera** [comment]
--noStrict simply disables type checking, not the "strict" option.

**Comment by zaoqi** [comment]
@evaera 
Neither can't work

**Comment by osyrisrblx** [comment]
`--noStrict` is being removed soon. Is there a reason you wanted to use it?

Since some of our code generation is type dependant, we cannot allow invalid TS during compilation since that would create invalid Lua.

Originally I added it for performance benefits but the compiler is slowly getting faster.

**Comment by Validark** [comment]
>slowly getting faster
I see what you did there.
