### ISSUE TITLE
Types like Uint8Array and Int32Array

### ISSUE THREAD

**Issue by test3211234** [roblox-ts/roblox-ts#2601]
I can't use types like Uint8Array and Int32Array. In what I'm writing the size and bytes is significant so I must use these types. How do I use these types? `Uint8Array` and `Int32Array`. 

Also, I thought all JavaScript was valid TypeScript, but JavaScript code gives me so many "x implicitly has an any type" errors.

**Comment by Fireboltofdeath** [comment]
All JavaScript is valid TypeScript code but that doesn't mean TypeScript won't give you type errors (in fact, that'd make TypeScript useless otherwise).

roblox-ts doesn't have `UInt8Array` or `Int32Array`, you most likely want Roblox's new `buffer` type which is semantically similar.

Also, you should ask for help in the [roblox-ts discord](https://discord.roblox-ts.com/) rather than using GitHub issues

**Comment by test3211234** [comment]
Oh, interesting. How do I make it work the same as it is used [here](https://github.com/deanm/omggif/blob/master/omggif.js)? (Search Uint8Array and Int32Array). Also, how do I get rid of the type errors? Shouldn't be a problem because lua is not even strongly typed should it? And I don't have Discord and they won't let me make an alt so I just don't use it.

**Comment by Fireboltofdeath** [comment]
`new UInt8Array(len)` -> `buffer.create(len)`
`array[i] = v` -> `buffer.readu8(array, i)`/`buffer.writeu8(array, i, v)`

`UInt32Array` is similar but buffers use byte offsets, so you must multiply your indices by `4` and use `buffer.readu32`/`buffer.writeu32`

Also, roblox-ts requires correctly typed TypeScript code to generate the proper emit, as it is dependent on type information. We have limited support for `any` and using it may result in incorrect behavior.

**Comment by test3211234** [comment]
Ok, by the way I was saying int32array not uint32array. And one more question, can I use external libraries/npm packages like sharp: https://www.npmjs.com/package/sharp?
