### ISSUE TITLE
Add --init to create new blank project with reasonable defaults

### ISSUE THREAD

**Issue by evaera** [roblox-ts/roblox-ts#278]

**Comment by Validark** [comment]
I think this is a great idea. Steps 2-6 from [project-folder-setup](https://roblox-ts.github.io/docs/quick-start#project-folder-setup) could be encapsulated into this one step. The question is, which steps (if not all) do you think should be performed automatically by `rbxtsc --init`? Personally, I think we should perform steps 3, 4, and 5 for the person that executes that command. I think we should make people perform steps 2 and 6 manually so that people unfamiliar with npm can run learn by running those commands themselves.

I think it would also be cool to see a `tslint` file being created, as well as `prettier` files. I think we should be highly recommending that people use both of these tools. In fact, for people who are unfamiliar with the tools available, we should have a list on the roblox-ts website with links to VSCode plugins we recommend.

**Comment by evaera** [comment]
We should probably just mirror tsc --init

**Comment by Validark** [comment]
Perhaps we could have:
```
rbxtsc --init game
rbxtsc --init bundle
rbxtsc --init package
```
