### ISSUE TITLE
RuntimeLib array helper functions should probably use i,v in pairs

### ISSUE THREAD

**Issue by filimunger** [roblox-ts/roblox-ts#343]
without proper loops, data can be drastically overlooked, for example:
```ts
let arr = []
arr[10] = true
arr.map((v) => print(v))
```
will print nothing

**Comment by Validark** [comment]
This is by design, done for performance reasons. In roblox-ts, an array is defined as having the length returned by the `#` operator. That means we don't support sparse arrays any more than Lua does (which it does to an extent). This is documented here: https://roblox-ts.github.io/docs/usage/unsupported-features

**Comment by Validark** [comment]
You should instead use a Map or Set.
