### ISSUE TITLE
Disallow Getters/Setters

### ISSUE THREAD

**Issue by osyrisrblx** [roblox-ts/roblox-ts#457]
#36 #55 

After many attempts at trying to find a suitable solution for getters/setters, I think it's best to disallow their usage entirely. I'll use this issue to go over attempts we've made at implementation and why they were not good enough.

**1. Compiling `get foo() {}` -> `getFoo() {}`**
This is what we started with but it ended up having a lot of issues.
For example, if you have:
- type `A` which has `foo` as a getter
- type `B` which has `foo` as a normal field
- type `C` which is `A & B`
How does `C.foo` compile?

We tried to address this by banning the usage of indexing union types with mixed getter/non-getter fields.

However, this problem becomes really hard to solve when you have things like:
```TS
interface X {
    value: number;
}
function foo(x: X) {}
```
It's increasingly difficult to understand what `x.value` is inside of `foo` from a static perspective.

**2. Making __index and __newindex into functions**
I see this as non-viable for performance reasons. If you make __index a function, it immediately incurs a large performance penalty for _any_ indexing. And while performance penalties should not completely disallow the usage of a feature, I believe this penalty is more hidden than expected.

For example, if class `A` uses getters/setters and class `B` inherits from A, `B` will incur the same performance penalty even if it doesn't use getters/setters itself.

I don't think getters/setters are really all that useful to begin with. They can actually make your code _more_ complex and require _more_ code reuse than you'd have without them.

Finally, I think it's difficult to debug the performance implications of using getters/setters from a user perspective. If we allow getters/setters, `foo.bar` _may_ result in a function call or may result in a simple index. It's very hard to tell without looking at the compiled source code or the implementation details for `foo`.

**Comment by Validark** [comment]
I think getters and setters can be useful, particularly when wrapping Roblox instances like so:

```ts
class A {
    private Frame = new Instance("Frame");

    get AnchorPoint() {
        return this.Frame.AnchorPoint;
    }
}
```

That said, I really tried to come up with a solution for how we could macro these to function calls and even sometimes in-line macroing. I determined that any relatively-simple macro system would ultimately need to fallback on an `__index` or `__newindex` metamethod.

Now, there is a chance it **MIGHT** be possible to track the original definition of a property and check whether it is a getter/setter. The most optimal solution, then, would be to in-line-compile potential `__index` situations (computed property indexing) like so:
```ts
const me = new class Person {
    constructor(public firstName:string, public lastName: string) {};
    get fullName() {
        return `${this.firstName} ${this.lastName}`;
    }
}

const f = (s: "firstName" | "lastName" | "fullName") => me[s];
print(f("fullName"));
print(f.fullName)
```
Btw, I am assuming that `get x()` is macro'd to `getX()`, where the conversion algorithm is `"get" + name.firstLetterUpper()`
```lua
-- Compiled by Validark's imagination v1.5.1
local _0;
do
	local Person = {};
	Person.__index = {};
	Person.new = function(...)
		return Person.constructor(setmetatable({}, Person), ...);
	end;
	Person.constructor = function(self, firstName, lastName)
		self.firstName = firstName;
		self.lastName = lastName;
		return self;
	end;
	function Person.__index:getFullName(self)
		return self.firstName .. " " .. self.lastName;
	end;
	Person._getters = { fullName = Person.__index.getFullName };
	_0 = Person;
end;
local me = (_0).new("Niles", "Validark");
local function f(s)
	local _0 = me._getters[s];
	if _0 then
		_0 = _0(me);
	else
		_0 = me[s];
	end;
end;
print(f:getFullName());
```
You could also do cool things like macroing getters/setters that just interface with an internal object, like in the first example, where `A.AnchorPoint` could be compiled to `A.Frame.AnchorPoint` for both setting and getting (when the circumstances are correct). For the getter (and the setter logic would be similar), the optimization can occur when the stars align for the following conditions:

- if the getter is a single statement, which is a return-statement
- if the getter returns a `propertyAccessExpression.propertyAccessExpression.propertyAccessExpression`, beginning with `this`
- if the value being returned is a non-function (if it were a function, in-lining it would change which object would be passed as `self`)

In order to do all this, you would need some good guards: Firstly, you would need to check to make sure the macros don't overlap with defined methods. In other words, if `get fullName() {}` and `getFullName() {}` both exist, then it should error. The other guard necessary would be to account for the example Osyris brought up in the previous post: You would need to disallow passing as a parameter instances of a class with getters/setters into a function whose expected type doesn't line up with the right properties as having getters and setters (although if it only uses members which actually exist, it would be fine). You would also need to guard against union types which have getters/setters for a member in one object but not in the other, which would be the same logic as the aforementioned parameter case. If those properties have the potential to be accessed, it should error (either through propertyAccessExpression or ambiguous computedPropertyExpressions, although if that is too complicated to detect *you could* just error if there is a union which could eventually lead to invalid behavior).

If the types sufficiently hold onto the aforementioned data, the system I described *could* be implemented. It would be pretty difficult and would take some time to get right. However, I am not motivated to implement this at present. It would be a lot of work for very little reward. Unless somebody wants to submit one heck of a fantastic PR for this that can pass a ton of test cases or pay someone else to do so, I fully support banning getters and setters until further notice.

**Comment by Validark** [comment]
Also, this case could probably be banned. https://github.com/TypeScriptToLua/TypeScriptToLua/issues/576

**Comment by JamieFristrom** [comment]
Sadface. Those getters and setters would have been real nice to make proxies for Roblox objects.
