### ISSUE TITLE
Promise.spawn causes 'Maximum event re-entrancy' errors 

### ISSUE THREAD

**Issue by mdnorman** [roblox-ts/roblox-ts#668]
## Version

**roblox-ts:** 0.2.12

**@rbxts/types:** 1.0.235

## Description
When using `Promise.spawn` to start processes that may have Wait blocks in them (such as `DataTable2.Get()` and `DataTable2.GetTable()`), if there are many spawns in a short time, then I get the following error:

```
Maximum event re-entrancy depth exceeded for BindableEvent.Event
While entering function defined in script 'ReplicatedStorage.rbxts_include.Promise', line 200
```

If I replace `Promise.spawn(myFunc)` with the following, I do not run into any issues:
```
const co = coroutine.create(myFunc);
coroutine.resume(co);
```

## Minimal Reproduction

Create a promise out of a function that uses a Wait(), and start dozens of these promises, and you should be able to reproduce.

**Expected behavior:**
Promise.spawn shouldn't cause issues when there are hundreds or even thousands of promises executing at once in the system

**Current behavior:**
Promise.spawn will sometimes cause the system to crash with several hundred promises started using this function.

**Comment by osyrisrblx** [comment]
Interesting, I haven't seen this before!

Our promises are backed by RemoteEvent objects because coroutines on Roblox currently have a few well known bugs. I will investigate this.

**Comment by evaera** [comment]
`Promise.spawn` reuses the same promise every time it's called, so if the promise body kicks off more promises the call stack will apparently grow to a point where Roblox will no longer allow firing the same event from within itself.

You can use `coroutine.wrap` and get the same effect as using `Promise.spawn`, and it won't have this problem. The only reason we use `Promise.spawn` with BindableEvents is because coroutines reset the stack trace so it's difficult to diagnose bugs. 

We could make a new BindableEvent every time to solve this problem, I don't think it would be too much overhead. `await` already creates a new BindableEvent for each time you use it, so this is not much compared to that.

**Comment by mdnorman** [comment]
If it helps the investigation, I created a `promisify` function to help me convert serial code that uses `Wait()`:

```
export const promisify = <T>(callback: () => T) => new Promise<T>((resolve, reject) =>
  Promise.spawn(() => {
    try {
      resolve(callback());
    } catch (e) {
      reject(e);
    }
  }));
```

When I replaced it with the following code, it solves all of the binding issues:
```
export const startAsync = (callback: () => void) => {
  const co = coroutine.create(callback);
  coroutine.resume(co);
};

export const promisify = <T>(callback: () => T) => new Promise<T>((resolve, reject) => {
  startAsync(() => {
    try {
      resolve(callback());
    } catch (e) {
      reject(e);
    }
  });
});
```
