### ISSUE TITLE
rojo.json files break rbxtsc -w

### ISSUE THREAD

**Issue by filimunger** [roblox-ts/roblox-ts#75]
![aa](https://user-images.githubusercontent.com/38803627/47947611-f131fa80-deed-11e8-80c0-694020e7681d.PNG)
always happens with the file in the root dir, moving the file to a different folder is a temporary fix

**Comment by TripleFrequency** [comment]
Also, you mentioned this is happening when running in watch mode, does it work when **not** in watch mode?

Could you provide your `rojo.json`, `tsconfig.json`, and a picture or description of your file structure? It would be helpful in diagnosing this issue.

**Comment by Intric** [comment]
`{
    "compilerOptions": {
        "outDir": "out",
        "rootDir": "src",
        "module": "commonjs",
        "strict": true,
        "noLib": true,
        "downlevelIteration": true,
        "declaration": false,
        "target": "es6",
        "typeRoots": [
            "rbx-types"
        ]
    },
    "typeAcquisition": {
        "enable": true
    }
}`
![capture](https://user-images.githubusercontent.com/38803627/47948100-03b13180-def8-11e8-87e4-6deccb328e1b.PNG)

I don't think this is the fault of the rest of the workspace, since by relocating rojo temporarily for -w, I can add it back later and then execute the project as normal for a session

**Comment by osyrisrblx** [comment]
Closing this in favor of Rojo 0.5 support in the future
