### ISSUE TITLE
Interfaces shouldn't be imported at run-time

### ISSUE THREAD

**Issue by TripleFrequency** [roblox-ts/roblox-ts#79]
In TypeScript, interfaces are completely erased at run-time.

This is same within this project: an exported interface is available to be used as a type in other files, but it is not actually exported. Importing should be the same way. Imports of interfaces shouldn't be compiled.

**Comment by osyrisrblx** [comment]
This looks like an oversight, good catch.

**Comment by vocksel** [comment]
Would just like to bump this to point out that a file that only exports an interface results in a runtime error.

```typescript
export interface User {
    userId: string
    appearanceId: string
}
```

compiles to:

```lua
return nil;
```

Which is only a problem because the file that the interface is in gets imported.

![image](https://user-images.githubusercontent.com/3081936/52459016-b49b1e00-2b30-11e9-8f14-16039cd7eadf.png)

In this sample, UserAction resolves to nil because the `actions` module its inside of returns a table from `export`. Whereas attempting to index `User` results in an error because the `types` module returns nil.
